apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: "yolo_backend:v1.1"
          ports:
            - containerPort: 3001  
          env:
            - name: MONGODB_URI
              value: mongodb://database:27017/ecommerce
